### PR TITLE
Add dnsPolicy option

### PR DESCRIPTION
**Pull request by darox**
This commit adds the possibility of specifying
the dnsPolicy.

### CODE REVIEW

**Comment by pmoscode** [comment]
Could you also add the "dnsConfig" property? This is useful for those, who set "dnsPolicy: none"
(https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#pod-dns-config)

**Comment by pmoscode** [comment]
I just commited the first bunch of Helm unittests.
Could you also add some unittests for your change?

**Comment by pmoscode** [comment]
Thanks a lot, and one remark: If you want to see your commit messages in the CHANGELOG.md, please use Conventional Commits (https://www.conventionalcommits.org/en/v1.0.0/)

**Comment by darox** [comment]
@pmoscode Sorry for the delay, I was busy with other things. It was actually the first time for me to write helm unit tests. I hope you're satisfied with the tests I have added, otherwise, let me know your improvement proposals.

**Comment by pmoscode** [comment]
And, if you add this test case:

```yaml
 - it: should render dnsConfig only once
    template: templates/deployment.yaml
    set:
      dnsPolicy: "None"
      dnsConfig.nameservers[0]: "1.1.1.1"
    asserts:
      - lengthEqual:
          path: spec.template.spec.dnsConfig
          count: 1
```

it will fail, because it will try to render dnsConfig twice, which is even not possible in yaml.

**Comment by pmoscode** [comment]
So, the conditions in the deployment.yaml are incomplete.
Beside that, the tests look great. :)

**Comment by pmoscode** [comment]
@darox At line 39 in the test you say "it: should render dnsConfig if dnsPolicy key is set to None and dnsConfig is set".
But "dnsPolicy" is not set to "none" in the "set" property of the test, am I right? Only "nameservers" and "searches" are set.

This is what I tried to demonstrate here: https://github.com/pmoscode-helm/jdownloader2/pull/2#issuecomment-1568100645

**Pull request closed without merging**
